version: '3'

volumes:
  pgdatasource:

services:
  zprefix-db:
    image: postgres
    restart: always
    environment: 
     - DATABASE_HOST=127.0.0.1
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=docker
     - POSTGRES_PORT=5432
     - POSTGRES_DB=zprefix
    ports:
     - '5432:5432'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - pgdatasource:/var/lib/postgresql/data

  zprefix-api:
    build: api/
    depends_on:
      zprefix-db:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment: 
      - NODE_ENV=development
      - DATABASE_HOST=zprefix-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_PORT=5432
      - POSTGRES_DB=zprefix
    volumes:
      - type: bind
        source: ./api
        target: /app
    command: npm run start:dev

  zprefix-ui:
    build: ui/
    depends_on:
      - 'zprefix-api'
    ports:
      - '3001:3000'
    volumes:
      - type: bind
        source: ./ui/src
        target: /app/src